### PR TITLE
Added new apps

### PR DESCRIPTION
**Pull request by jlandes**

### CODE REVIEW

**Comment by quanglam2807** [comment]
Thanks a lot. Do you think this icon would be better?
redbox-icon

**Comment by jlandes** [comment]
That one would work.

**Comment by quanglam2807** [comment]
Nice! Can you make a commit?

**Comment by jlandes** [comment]
Yes, I will later today.

**Comment by jlandes** [comment]
The icon has been replaced and committed.

**Comment by quanglam2807** [comment]
Thanks a lot, @jlandes!

**Pull request merged**
