### PR TITLE
Add/iconresize

### PR DESCRIPTION
**Pull request by VirgileACM**
Added script fixicon.py to fix individual icon. The goal is to integrate it in pack.js.

From code:

# REQUIREMENTS
Requires Python 3
To install required packages, run in terminal: $ pip install pillow numpy scipy matplotlib tqm

# USE IN TERMINAL
Implicit call:
-> $ python3 fixicon.py 'path2icon' SIZE_RESIZE PAD
Explicit call:
-> $ python3 fixicon.py -path 'path2icon' -size SIZE_RESIZE -pad PAD
SIZE_RESIZE and PAD are optionals in both cases.

### CODE REVIEW

**Comment by quanglam2807** [comment]
This looks amazing! If this thing works, you should consider to turn it into an independent package. I think it will help a lot of people. I would be more than happy to help you :)

**Comment by quanglam2807** [comment]
@VirgileACM Can I delete `auto-icon-resizer.py`?

**Comment by VirgileACM** [comment]
@quanglam2807 Great, I hope it will work well, let me know when the update is live, I am looking forward to seeing it in web catalog! 👍

Yes, I think we can delete auto-icon-resizer.py, it was more of a prototype.

I actually might be also interested in making the code available more widely. It's true that it might be helping others in web or app dev. Thanks for showing interest in making it a package, I will look into it and keep you in the loop ;)

**Comment by quanglam2807** [comment]
@VirgileACM Great, I'm looking forward to it! Also, the update is live. Thanks a lot for helping.

**Comment by VirgileACM** [comment]
@quanglam2807 As of today, I still cannot seem to see the update. I'm running it on Mac and it didn't ask me for an update, still on WebCatalog v9.0.0. The icons clearly didn't change. Did I miss something?

**Comment by quanglam2807** [comment]
@VirgileACM Probably because of caching. Also, the icons are only updated on the server and you will need to update/reinstall your apps to have the new icons.

I checked Google Maps icon: https://icons.webcatalog.io/google-maps/google-maps-icon.png and it seems to be updated.

**Pull request merged**
